### ISSUE TITLE
QuasarF type and error handling

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-quasar#1]
I've experimented with two approaches for how we return values, given that we need to model failure somehow, and I assume we want a way to handle it not at the site of interpretation, but instead have some tools so we can catch, retry, etc.

Perhaps the most obvious way is to do something like this:

``` purescript
data QuasarF a
  = SomeOp (Either Error Unit → a)
```

But something else that would work would be to do this:

``` purescript
data QuasarF m a
  = SomeOp (m Unit → a)

-- or even:

data QuasarF m a
  = SomeOp (m Unit → m a)
```

The idea being that `m` would be left polymorphic when using `QuasarF` to define queries, but then when interpreting we can do something like this:

``` purescript
eval
  ∷ ∀ m
  . ( MonadError Error m
    , MonadAff ( ... effects ... ) m
    )
  ⇒ Natural (QuasarF m) m
```

The thinking being `Aff` already has `MonadError` baked in, so by having to `attempt` every computation to turn it into an `Either Error blah` we're not really using it to the full advantage.

I'm leaning more towards the first (`Either` based approach) as it's less unusual, but just wondered if anyone else had thoughts on how we might want to deal with error handling? @jdegoes @cryogenian @jonsterling

**Comment by jonsterling** [comment]
I think I prefer the first approach, at least from an algebraic point of view, but maybe with some more elaboration I could be convinced otherwise.

**Comment by cryogenian** [comment]
Finally tagless with type synonyms for actual run and tests? 

Is it possible to make something like

``` purescript
data QuasarF a = SomeOp (String-> a) | HandleError (Error -> a) 

attempt :: forall a. Quasar a -> Quasar (Either Error a) 
```

If not I like first more.

**Comment by garyb** [comment]
I don't think finally tagless would work here as `QuasarF` is potentially going to end up in a coproduct in `Slam`, so it needs a free-style interpreter.

I'll stick with the first thing for now, QuasarF itself is pretty simple so we can definitely try out a few things.

**Comment by jdegoes** [comment]
Yeah, I like the first approach too. That way, it's clear when something can fail or not, it doesn't complicate the type signature, and it doesn't promise that any error can be recovered from (which is the problem, possibly, with adding error recovery into the algebra).

**Comment by garyb** [comment]
Thanks all!
