### ISSUE TITLE
Resolve issues with Spark HDFS codecs

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-quasar#27]
See discussion here: https://github.com/slamdata/purescript-quasar/pull/26#discussion_r107148530

Looks like there is a mismatch with the encoder and decoder.

**Comment by Cmdv** [comment]
https://github.com/slamdata/purescript-quasar/blob/71c25f2116802356968fa46bd08650755e0f1852/src/Quasar/Mount/SparkHDFS.purs#L57

**Comment by garyb** [comment]
Opened an issue on Quasar, as the correct value is not documented currently: https://github.com/quasar-analytics/quasar/issues/1995
